apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: taskflow
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
  clusterIP: None # headless service dla StatefulSet
