# =======================================================
# service.yaml - Serwis sieciowy Nginx wystawiający aplikację
#
# Serwis typu NodePort. Pozwala na bezpośredni dostęp do aplikacji
# z systemu operacyjnego hosta za pomocą portu 30080.
# =======================================================
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: taskflow
spec:
  ports:
    - port: 80         # Port wewnętrzny usługi
      targetPort: 80   # Port docelowy w podzie Nginx
      nodePort: 30080  # Sztywny port zewnętrzny wystawiony na maszynie węzła
  selector:
    app: nginx
  type: NodePort       # NodePort umożliwia łatwy dostęp deweloperski

