# =======================================================
# ingress.yaml - Routing wejściowy (Ingress) klastra
#
# Definicja reguł routingu ruchu HTTP opartego na domenie.
# Umożliwia dostęp do aplikacji przez nazwę hosta 'taskflow.local'.
# =======================================================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taskflow-ingress
  namespace: taskflow
spec:
  rules:
    - host: taskflow.local # Mapowanie ruchu kierowanego na domenę taskflow.local
      http:
        paths:
          - path: /prometheus
            pathType: Prefix
            backend:
              service:
                name: prometheus-svc
                port:
                  number: 9090
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: grafana-svc
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-svc # Kierowanie ruchu do serwisu Nginx
                port:
                  number: 80

