# =======================================================
# namespace.yaml - Dedykowana przestrzeń nazw (Namespace)
#
# Izolacja logiczna zasobów aplikacji TaskFlow w klastrze.
# Zapobiega konfliktom nazw z innymi aplikacjami.
# =======================================================
apiVersion: v1
kind: Namespace
metadata:
  name: taskflow
  labels:
    app.kubernetes.io/name: taskflow
    app.kubernetes.io/part-of: taskflow
