# =======================================================
# service.yaml - Serwis sieciowy dla bazy danych PostgreSQL
#
# Definicja punktu dostępowego wewnątrz klastra (wewnętrzny DNS).
# =======================================================
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: taskflow
spec:
  ports:
    - port: 5432       # Port, na którym usługa nasłuchuje w sieci klastra
      targetPort: 5432 # Port w kontenerze docelowym podu
  selector:
    app: postgres      # Powiązanie serwisu z podami posiadającymi etykietę app: postgres
  clusterIP: None      # Serwis typu Headless (brak wirtualnego IP) - wymagany do orkiestracji StatefulSet

